---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    key_groups:
      - age:
          - age1z4yxmquef67lkx6wtrl00wact2wuy2y2zf7fk63egejh54h3gp2sqkq9p6
  - path_regex: cluster/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1z4yxmquef67lkx6wtrl00wact2wuy2y2zf7fk63egejh54h3gp2sqkq9p6
