---
vm_ip_address: "{{ vm_network }}20"  # Required
docker_ip: "{{ vm_ip_address }}"
vm:
  # name: docker   # Default is ansible magic var `inventory_hostname_short` if omitted
  ipconfig:
    ipconfig0: "ip={{ vm_ip_address }}/{{ vm_netmask }},gw={{ vm_gateway }}"
  id: 200   # Required
  hdd_size: "100G"
  memory: 7000
