---

- hosts: k3s_cluster
  name: Reset k3s cluster
  gather_facts: true
  become: true
  roles:
    - role: k3s/reset
    - role: k3s/raspberrypi
      vars: {state: absent}
  post_tasks:
    - name: Reboot and wait for node to come back up
      reboot:
        reboot_timeout: 3600
