#######################################
### THIS FILE IS MANAGED BY ANSIBLE ###
###    PLEASE MAKE CHANGES THERE    ###
#######################################

http:
  middlewares:
    middlewares-basic-auth:
      basicAuth:
        # Add users below if you wish, but i do it in htpasswd file (usersFile below)
        # users:
        #   - "user:$apsdfs.$EntPC0w3FtswWvC/6fTVJ7IUVtX1"
        realm: "Traefik2 Basic Auth"
        usersFile: "/run/secrets/htpasswd"
        # usersFile: "/shared/.htpasswd" # be sure to mount the volume through docker-compose.yml

    middlewares-rate-limit:
      rateLimit:
        average: 100
        burst: 50

    middlewares-https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true

    middlewares-compress:
      compress: {}

    # https://stackoverflow.com/questions/49717670/how-to-config-upload-body-size-restriction-in-traefik
    middlewares-buffering:
      buffering:
        maxRequestBodyBytes: 10485760   # 10mb
        memRequestBodyBytes: 2097152    # 2mb
        maxResponseBodyBytes: 10485760  # 10mb
        memResponseBodyBytes: 2097152   # 2mb
        retryExpression: "IsNetworkError() && Attempts() <= 2"

######## Available Header Options:
##### https://github.com/unrolled/secure#available-options
##### https://docs.traefik.io/middlewares/headers/
# A great resource for these headers is your preferred browser's docs. Firefox: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers
# https://developers.google.com/search/reference/robots_meta_tag
# https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Clickjacking_Defense_Cheat_Sheet.md
# CSP for VNC: https://github.com/cockpit-project/cockpit/pull/5932
# Check headers here, don't include OAuth when checking headers, otherwise you are checking google's headers: https://securityheaders.com
# or check them here: https://observatory.mozilla.org/

# CAUTION: Any headers defined in docker-compose (yml) will OVERWRITE ALL of the headers defined below.

    middlewares-secure-headers:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
        accessControlMaxAge: 100
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        stsSeconds: 63072000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        # customFrameOptionsValue: "allow-from https:{{ domain_name }}" #CSP takes care of this but may be needed for organizr.
        # Sniffing will happen regardless of whether the content is trusted or untrusted. See security.stackexchange.com/a/11761/2379 . It will break your site in subtle ways. Always disable sniffing if you do not like surprises
        contentTypeNosniff: true
        # browserXssFilter: true
        referrerPolicy: "same-origin"
        PermissionsPolicy: "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=(), vr=()" # fullscreen=*
        customResponseHeaders:
          X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex"
          server: ""

    middlewares-oauth:
      forwardAuth:
        address: "http://oauth:{{ oauth_port }}" # Make sure you have the OAuth service in docker-compose.yml
        trustForwardHeader: true
        authResponseHeaders:
          - "X-Forwarded-User"

    middlewares-authelia:
      forwardAuth:
        address: "http://authelia:9091/api/verify?rd=https://auth.{{ domain_name }}"
        trustForwardHeader: true
        authResponseHeaders:
          - "Remote-User"
          - "Remote-Groups"
          - "Remote-Name"
          - "Remote-Email"
