---
# - name: Check if Hass is already running
#   ansible.windows.win_powershell:
#     script: (Get-Process -Name hass-workstation-service).ProcessName
#   register: hass_result
#   ignore_errors: true

# # - name: debug hass_result
# #   debug:
# #     msg: "the result: {{ item.fully_qualified_error_id }}"
# #   loop: "{{ hass_result.error }}"

# # Resource that helped -> https://www.middlewareinventory.com/blog/ansible-dict-object-has-no-attribute-stdout-or-stderr-how-to-resolve/
# - name: Install hass-workstation-service
#   win_package:
#     path: https://hassworkstationstorage.z6.web.core.windows.net/publish/setup.exe
#   when: "'Cannot find a process' in item.output"
#   loop: "{{ hass_result.error }}"

# - name: Install HASS.agent
#   win_package:
#     path: https://github.com/LAB02-Research/HASS.Agent/releases/latest/download/HASS.Agent.Installer.exe
