---
- name: Create directory structure
  ansible.windows.win_file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ img_dir }}"
    - "{{ wsl_install_location }}"

- name: Download ubuntu cloud image
  win_get_url:
    url: "{{ ubuntu_img_url }}"
    dest: "{{ img_dir }}\\{{ ubuntu_img_url | basename }}"

- name: Create wsl instance from cloud image
  ansible.windows.win_command: wsl --import {{ wsl_instance_name }} {{ wsl_install_location }} {{ img_dir }}\{{ ubuntu_img_url | basename }}

- name: Set default wsl instance
  ansible.windows.win_command: wsl --set-default {{ wsl_instance_name }}
  when: wsl_set_default

- name: Setup non-root user
  ansible.windows.win_command: wsl -d {{ wsl_instance_name }} sh -c "addgroup '{{ main_user }}' && adduser --uid '1000' --ingroup '{{ main_user }}' '{{ main_user }}' && usermod --append --groups 'admin' '{{ main_user }}' && echo '{{ main_user }}:{{ main_pass }}' | chpasswd"
  when: wsl_set_default

- name: set default WSL 2 user
  ansible.windows.win_powershell:
    script: |
      Get-ItemProperty Registry::HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss\*\ DistributionName |
      Where-Object -Property DistributionName -eq "{{ wsl_instance_name }}" |
      Set-ItemProperty -Name DefaultUid -Value 1000

- name: Set further defaults to WSL instance manually
  pause:
    prompt: |
      Press Ctrl+c and then "a" to abort. But please do the following first...

      Please go manually configure the following in windows terminal:
        - Name is: '{{ wsl_instance_name }}'
        - Command Line should be something like: `C:\Windows\system32\wsl.exe -d {{ wsl_instance_name }}`
        - Starting Directory: '~'
        - Tab title: '{{ wsl_instance_name }}'
      Please also ensure in the windows docker desktop app, that docker wsl integration is enabled on THIS WSL instance (it's per instance).
      Also some commands to assist setup:
        sudo apt update
        sudo apt upgrade
        sudo apt install make
        git clone https://gitlab.com/sami-group/homelab.git
        cd homelab
        make setup
          * Copy vault password
        make wsl-personal
