---
# Use this file to store secrets like usernames and passwords.
# Learn more at https://www.home-assistant.io/docs/configuration/secrets/

# Use this tool (https://latlongdata.com/elevation/), find your place and copy your values below:
home_name: {{ hass.home_name }}
latitude_home: {{ hass.latitude_home }}
longitude_home: {{ hass.longitude_home }}
elevation: {{ hass.elevation }}
time_zone: {{ tz }}
currency: {{ hass.currency }}

external_url: {{ hass.external_url }}
internal_url: {{ hass.internal_url }}

# Mariadb URL - @docker_ip because hass in docker has host networking. Change as desired.
mariadb_url: mysql://{{ mariadb.user }}:{{ mariadb.password }}@{{ docker_ip }}:{{ mariadb_port }}/{{ mariadb.database }}?charset=utf8mb4

# List of trusted proxies, consisting of IP addresses or networks,
# that are allowed to set the X-Forwarded-For header.
# Can be a subnet, e.g. 10.x.x.x/24
http_trusted_proxies:
{% for trusted_proxy in hass.http_trusted_proxies %}
  - "{{ trusted_proxy }}"
{% endfor %}

local_network_lan: "{{ local_network_lan }}"
local_network_homelab: "{{ local_network_homelab }}"

# My PC static IP address
pc_host: "{{ hass.pc_host }}"
docker_host: "{{ hass.docker_host }}"
influxdb_bucket: "{{ influxdb.hass_bucket_name }}"
influxdb_port: "{{ influxdb_port }}"
influxdb_auth_token: "{{ influxdb.hass_token }}"
# This is in the URL after /orgs
influxdb_organization: "{{ influxdb.org_id }}"
influxdb_glob_entities:
{% for glob_entity in hass.influxdb_glob_entities %}
  - "{{ glob_entity }}"
{% endfor %}

# Google Project ID - This used to be valid jinja, reuse if you want google re-integrated.
# google_project_id: "{ hass.google_project_id }"

# MQTT broker username/password for the docker container:
mqtt_username: "{{ hass.mqtt_username }}"
mqtt_password: "{{ hass.mqtt_password }}"
mqtt_port: "{{ mosquitto_http_port }}"
