---
#######################################
### THIS FILE IS MANAGED BY ANSIBLE ###
###    PLEASE MAKE CHANGES THERE    ###
#######################################

version: "3.7"

########################### EXTENSION FIELDS

# To use this put this block in your service: "<<: *logging"
x-logging: &logging
  logging:
    driver: loki
    options:
      loki-url: "http://${SERVER_IP}:${LOKI_PORT}/loki/api/v1/push"

########################### NETWORKS

networks:
  traefik_proxy:
    name: traefik_proxy
    external: true

########################### SERVICES

services:
  # Homer - full static html/js dashboard
  # https://hub.docker.com/r/b4bz/homer
  # Configuration here -> https://github.com/bastienwirtz/homer/blob/main/docs/configuration.md
  # Icons -> https://github.com/NX211/homer-icons#homer-icons
  homer:
    container_name: homer
    image: b4bz/homer:latest
    init: true
    restart: always
    networks:
      - traefik_proxy
    ports:
     - "${HOMER_PORT}:8080"
    volumes:
      - ${DOCKERDIR}/appdata/homer:/www/assets
    environment:
      UID: $PUID
      GID: $PGID
      TZ: $TZ
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.homer-rtr.entrypoints=https"
      - "traefik.http.routers.homer-rtr.rule=Host(`home.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.homer-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.homer-rtr.service=homer-svc"
      - "traefik.http.services.homer-svc.loadbalancer.server.port=8080"
    <<: *logging
