---
#######################################
### THIS FILE IS MANAGED BY ANSIBLE ###
###    PLEASE MAKE CHANGES THERE    ###
#######################################

version: "3.7"

########################### EXTENSION FIELDS
# Re-usable code so we're not duplicating these everywhere

# Default TZ, uid and pid
# To use this put this block in your service in the environments block: "<<: *default-tz-uid-gid"
x-environment: &default-tz-uid-gid
  TZ: $TZ
  PUID: $PUID
  PGID: $PGID

# To use this put this block in the root of your service: "<<: *logging"
x-logging: &logging
  logging:
    driver: loki
    options:
      loki-url: "http://localhost:${LOKI_PORT}/loki/api/v1/push"

########################### NETWORKS

networks:
  defaulty:
    name: defaulty
    external: true
  traefik_proxy:
    name: traefik_proxy
    external: true
  socket_proxy:
    name: socket_proxy
    external: true

########################### SECRETS

secrets:
  htpasswd:
    file: ${DOCKERDIR}/secrets/htpasswd
  cloudflare_email:
    file: ${DOCKERDIR}/secrets/cloudflare_email
  cloudflare_api_key:
    file: ${DOCKERDIR}/secrets/cloudflare_api_key
  plex_claim:
    file: ${DOCKERDIR}/secrets/plex_claim
  traefik_pilot_token:
    file: ${DOCKERDIR}/secrets/traefik_pilot_token
  gmail_email:
    file: ${DOCKERDIR}/secrets/gmail_address
  # This gmail password needs to be the APPLICATION password, not your main login one.
  # https://support.google.com/accounts/answer/185833?hl=en
  gmail_app_pass:
    file: ${DOCKERDIR}/secrets/gmail_app_pass
  services_username:
    file: ${DOCKERDIR}/secrets/services_username
  services_password:
    file: ${DOCKERDIR}/secrets/services_password

########################### SERVICES

services:

  # Jellyfin - Media Server
  # https://hub.docker.com/r/jellyfin/jellyfin
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin:latest
    init: true
    restart: unless-stopped
    networks:
      traefik_proxy:
        ipv4_address: 192.168.90.152 # You can specify a static IP
    devices:
      - /dev/dri:/dev/dri # For harware transcoding
    security_opt:
      - no-new-privileges:true
    ports:
      - "${JELLYFIN_PORT}:8096"
      - "8920:8920" # Emby also uses same port if running both
    environment:
      user: ${UID}:${GID}
      UMASK_SET: 022
    volumes:
      - ${DOCKERDIR}/appdata/jellyfin:/config
      - ${DOCKERDIR}/appdata/shared/jellyfin/metadata:/config/metadata
      - ${USERDIR}/mount/movies:/data/media/movies
      - ${USERDIR}/mount/tv:/data/media/tv
      - /dev/shm:/data/transcode # Offload transcoding to RAM if you have enough RAM
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.jellyfin-rtr.entrypoints=https"
      - "traefik.http.routers.jellyfin-rtr.rule=Host(`jellyfin.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.jellyfin-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.jellyfin-rtr.service=jellyfin-svc"
      - "traefik.http.services.jellyfin-svc.loadbalancer.server.port=$JELLYFIN_PORT"
