---
#######################################
### THIS FILE IS MANAGED BY ANSIBLE ###
###    PLEASE MAKE CHANGES THERE    ###
#######################################

version: "3.7"

########################### EXTENSION FIELDS
# Re-usable code so we're not duplicating these everywhere

# Default TZ, uid and pid
# To use this put this block in your service in the environments block: "<<: *default-tz-uid-gid"
x-environment: &default-tz-uid-gid
  TZ: $TZ
  PUID: $PUID
  PGID: $PGID

# To use this put this block in the root of your service: "<<: *logging"
x-logging: &logging
  logging:
    driver: loki
    options:
      loki-url: "http://localhost:${LOKI_PORT}/loki/api/v1/push"

########################### NETWORKS

networks:
  defaulty:
    name: defaulty
    external: true
  traefik_proxy:
    name: traefik_proxy
    external: true
  socket_proxy:
    name: socket_proxy
    external: true

########################### SECRETS

secrets:
  htpasswd:
    file: ${DOCKERDIR}/secrets/htpasswd
  cloudflare_email:
    file: ${DOCKERDIR}/secrets/cloudflare_email
  cloudflare_api_key:
    file: ${DOCKERDIR}/secrets/cloudflare_api_key
  plex_claim:
    file: ${DOCKERDIR}/secrets/plex_claim
  traefik_pilot_token:
    file: ${DOCKERDIR}/secrets/traefik_pilot_token
  gmail_email:
    file: ${DOCKERDIR}/secrets/gmail_address
  # This gmail password needs to be the APPLICATION password, not your main login one.
  # https://support.google.com/accounts/answer/185833?hl=en
  gmail_app_pass:
    file: ${DOCKERDIR}/secrets/gmail_app_pass
  services_username:
    file: ${DOCKERDIR}/secrets/services_username
  services_password:
    file: ${DOCKERDIR}/secrets/services_password

########################### SERVICES

services:

  # Motioneye NVR Surveillance Software
  # Default user = admin (Leave password blank)
  # Install in docker instructions -> https://github.com/ccrisan/motioneye/wiki/Install-In-Docker
  # Docker hub -> https://hub.docker.com/r/ccrisan/motioneye/
  motioneye:
    container_name: motioneye
    image: "ccrisan/motioneye:master-amd64"
    init: true
    restart: always
    # user: root
    networks:
      traefik_proxy:
        ipv4_address: 192.168.90.156 # You can specify a static IP
    ports:
      - 8765:8765
    deploy:
      resources:
        limits:
          cpus: '2'
          # memory: 50M
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${DOCKERDIR}/appdata/motioneye/etc:/etc/motioneye"
      - "${USERDIR}/mount/motioneye:/var/lib/motioneye"
    environment:
      TZ: ${TZ}
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.motioneye-rtr.entrypoints=https"
      - "traefik.http.routers.motioneye-rtr.rule=Host(`motioneye.$DOMAINNAME`, `cam.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.motioneye-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.motioneye-rtr.service=motioneye-svc"
      - "traefik.http.services.motioneye-svc.loadbalancer.server.port=8765"
