---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: Australia/Sydney
  METALLB_LB_RANGE: 192.168.30.91-192.168.30.99
  METALLB_K8S_GATEWAY_ADDR: 192.168.30.92
  METALLB_INGRESS_ADDR: 192.168.30.93
