---
- name: Apt Upgrade
  apt:
    name: '*'
    state: latest
    update_cache: true

- name: Add apt repo's
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - 'ppa:yktooo/ppa'

- name: Install required packages
  apt:
    state: present
    pkg:
      - wget
      - curl                   # Docker
      - telnet
      - net-tools
      - logrotate
      - ca-certificates   # Docker
      - gnupg               # Docker
      - lsb-release        # Docker
      - htop
      - make
      - vim
      - stow
      - python3
      - python3-pip
      - cifs-utils
      - nfs-common
      - bash-completion
      - apt-transport-https
      - software-properties-common
      - jq
      - git
      - unzip
      - snapd
      - pwgen

- name: Install required GUI packages
  apt:
    state: present
    pkg:
      - gimp
      - flameshot
      - gnome-tweaks
      - vlc
      - appmenu-gtk3-module
      - indicator-sound-switcher
  when: has_gui is defined

- name: pip self-update
  pip:
    name: pip
    state: latest

- name: Install required python modules
  pip:
    name:
      - docker
      - passlib
      - pyyaml

- name: mark vundle dir as safe in git config
  community.general.git_config:
    name: safe.directory
    scope: global
    value: "{{ user_dir }}/.vim/bundle/Vundle.vim"

# Vundle install
- name: Clone Vundle
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: "{{ user_dir }}/.vim/bundle/Vundle.vim"
    clone: true
    update: true
  become_user: "{{ user_info.name }}"  # We want ownership of the repo to be the user that we're cloning to

- name: Install Snaps
  community.general.snap:
    name: "{{ item }}"
  with_list:
    - bitwarden
    - spotify
    - teams
    - mysql-workbench-community
  when: has_gui is defined

- name: Install Snaps (classic)
  community.general.snap:
    name: "{{ item }}"
    classic: true
  with_list:
    - slack
    - code
  when: has_gui is defined
