---
# ------------------------------------------- #
# Run this in every playbook before anything! #
# Therefore, keep this task list VERY simple! #
# ------------------------------------------- #

# Include var overrides
- name: Include playbook configuration.
  include_vars: "{{ item }}"
  with_fileglob:
    - "{{ playbook_dir }}/../vars/config.yml"

# Import bitwarden role - For obtaining passwords from bitwarden
# - import_role:
#     name: ansible-modules-bitwarden

### Work in progress - May migrate my vault to bitwarden..
# # Get all available fields for an entry
# - debug:
#     var: lookup('bitwarden', 'Ansible Vault', field='item')
