---
- name: Ensure virtualbox config dir exists
  ansible.builtin.file:
    path: /etc/vbox
    state: directory
    mode: '0755'

- name: Ensure virtualbox network config file exists
  ansible.builtin.file:
    path: /etc/vbox/networks.conf
    state: touch
    mode: '0644'

- name: Ensure virtualbox network config file updated
  ansible.builtin.blockinfile:
    path: /etc/vbox/networks.conf
    block: |
      * 10.0.0.0/8 192.168.0.0/16 172.16.0.0/12
      * 2001::/64

- name: Count number of vagrant plugins installed
  ansible.builtin.command:
    cmd: vagrant plugin list
  register: count_vagrant_plugins
  changed_when: false

- name: Install vagrant plugins
  ansible.builtin.command: vagrant plugin install virtualbox_WSL2 vagrant-vbguest vagrant-hosts
  changed_when: count_vagrant_plugins.stdout_lines | length < 3
